const JSZip = require('jszip');

async function createWebsiteZip(website) {
  const zip = new JSZip();

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${website.layout?.hero?.title || 'NeuroForge Website'}</title>
  <style>
    body { margin: 0; font-family: ${website.branding?.font || 'Arial'}; background: #020617; color: #f8fafc; }
    .hero { min-height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 2rem; text-align: center; }
    h1 { color: ${website.branding?.primaryColor || '#6d28d9'}; }
    p { color: ${website.branding?.secondaryColor || '#06b6d4'}; max-width: 760px; }
  </style>
</head>
<body>
  <div class="hero">
    <h1>${website.layout?.hero?.title || 'Generated by NeuroForge'}</h1>
    <p>${website.layout?.hero?.subtitle || 'AI generated web experience.'}</p>
  </div>
</body>
</html>`;

  zip.file('index.html', html);
  zip.file('scene-config.json', JSON.stringify(website.threejsScene || {}, null, 2));

  const buffer = await zip.generateAsync({ type: 'base64' });
  return `data:application/zip;base64,${buffer}`;
}

module.exports = { createWebsiteZip };
